""" 
⌛

CONFIGURE CLOUD OBJECT STORAGE. 
1.  READY TO ACCEPT DATA.
2.  EVERY DATA - metadata IN CLOUD OBJECT is checked and compared to current time.
3.  IF OUTCOME TIME IS > 10 MIN DELETE THE OBJECT FROM THE CLOUD - FREE UP SPACE.

"""